_.fore  # unused attribute (tests/_test.py:54)
fixture_color  # unused function (tests/conftest.py:9)
fixture_populated_colors  # unused function (tests/conftest.py:15)
Color  # unused class (object_colors/__init__.py:15)
_.populate_colors  # unused method (object_colors/__init__.py:185)
_.set  # unused method (object_colors/__init__.py:193)
